package ead_cw;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anjal
 */

import javax.swing.JOptionPane;

public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStudent = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnLecturer = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();
        btnAssesment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAMS(Smart Academic Management System)");

        btnStudent.setText("Student Mangement");
        btnStudent.addActionListener(this::btnStudentActionPerformed);

        btnReports.setText("View Reports");
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(this::btnAttendanceActionPerformed);

        btnLecturer.setText("Lecture Management");
        btnLecturer.addActionListener(this::btnLecturerActionPerformed);

        btnCourse.setText("Course Management");
        btnCourse.addActionListener(this::btnCourseActionPerformed);

        btnAssesment.setText("Assessment Results");
        btnAssesment.addActionListener(this::btnAssesmentActionPerformed);

        jLabel1.setText("STUDENT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnAttendance)
                        .addGap(30, 30, 30)
                        .addComponent(btnReports)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudent)
                            .addComponent(btnCourse))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAssesment)
                            .addComponent(btnLecturer))
                        .addGap(0, 21, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudent)
                    .addComponent(btnLecturer))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourse)
                    .addComponent(btnAssesment))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttendance)
                    .addComponent(btnReports)
                    .addComponent(btnLogout))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        new RegistrationForm().setVisible(true);
this.dispose();
        
        // This opens your registration form
RegistrationForm reg = new RegistrationForm(); 
reg.setVisible(true);

// This closes the Dashboard so you don't have too many windows open
this.dispose();
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        // Inside the button click event
ViewAttendance report = new ViewAttendance();
report.setVisible(true); // Open the report
this.dispose();          // Close the dashboard so they don't stack
        
        
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
                                                
    int response = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (response == javax.swing.JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        // TODO add your handling code here:
        
        new CourseForm().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerActionPerformed
        // TODO add your handling code here:
        new LecturerForm().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnLecturerActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
        new ViewAttendance().setVisible(true);
        new AttendanceForm().setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnAssesmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssesmentActionPerformed
        // TODO add your handling code here:
        // Create the new window
AssessmentForm assessment = new AssessmentForm(); 

// Make it appear
assessment.setVisible(true); 

// Close the current window so you don't have too many open
this.dispose();
    }//GEN-LAST:event_btnAssesmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssesment;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnLecturer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStudent;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
    }

