/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ead_cw;

/**
 *
 * @author anjal
 */
public class LecturerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LecturerForm.class.getName());

    /**
     * Creates new form LecturerForm
     */
    public LecturerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLecturerID = new javax.swing.JTextField();
        txtLecturerName = new javax.swing.JTextField();
        txtLecturerEmail = new javax.swing.JTextField();
        txtDept = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lecturer ID");

        jLabel2.setText("Lecturer Name");

        jLabel3.setText("Lecturer Email");

        jLabel4.setText("Department");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtLecturerID, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(txtLecturerName))
                    .addComponent(txtLecturerEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnBack)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLecturerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLecturerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
    // 1. Get the data from your specific Lecturer fields
    String id = txtLecturerID.getText();
    String name = txtLecturerName.getText();
    String email = txtLecturerEmail.getText();
    String dept = txtDept.getText();

    // 2. Connect to the 'sams' database
    java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sams", "root", "");

    // 3. Prepare SQL (Make sure you ran the CREATE TABLE command in phpMyAdmin first!)
    String sql = "INSERT INTO lecturers (lecturer_id, name, email, department) VALUES (?, ?, ?, ?)";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    
    pst.setString(1, id);
    pst.setString(2, name);
    pst.setString(3, email);
    pst.setString(4, dept);

    // 4. Execute and show success
    pst.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Lecturer Added Successfully!");
    
    con.close();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:txtLecturerID.setText("");
txtLecturerName.setText("");
txtLecturerEmail.setText("");
txtDept.setText("");
txtLecturerID.requestFocus(); // Puts the cursor back in the first box
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
    // 1. Connect to the 'sams' database
    java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sams", "root", "");

    // 2. Prepare the SQL Update Statement
    // We update name, email, and department WHERE the lecturer_id matches
    String sql = "UPDATE lecturers SET name = ?, email = ?, department = ? WHERE lecturer_id = ?";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    
    // 3. Set the values from your TextFields
    pst.setString(1, txtLecturerName.getText());
    pst.setString(2, txtLecturerEmail.getText());
    pst.setString(3, txtDept.getText());
    pst.setString(4, txtLecturerID.getText()); // This matches the 'WHERE' clause

    // 4. Execute the update
    int rowsUpdated = pst.executeUpdate();
    
    if (rowsUpdated > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lecturer Record Updated Successfully!");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No lecturer found with that ID.");
    }
    
    con.close();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        // 1. Ask the user for confirmation before deleting
int dialogResult = javax.swing.JOptionPane.showConfirmDialog(this, 
    "Are you sure you want to delete this lecturer?", "Warning", javax.swing.JOptionPane.YES_NO_OPTION);

if (dialogResult == javax.swing.JOptionPane.YES_OPTION) {
    try {
        // 2. Connect to the 'sams' database
        java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sams", "root", "");

        // 3. Prepare the SQL Delete Statement
        String sql = "DELETE FROM lecturers WHERE lecturer_id = ?";
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        
        // Use the ID from the text box to identify who to delete
        pst.setString(1, txtLecturerID.getText());

        // 4. Execute
        int rowsDeleted = pst.executeUpdate();
        
        if (rowsDeleted > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lecturer Deleted Successfully!");
            
            // 5. Clear the text boxes after deleting
            txtLecturerID.setText("");
            txtLecturerName.setText("");
            txtLecturerEmail.setText("");
            txtDept.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lecturer ID not found.");
        }
        
        con.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // 1. Create an instance of your Dashboard
Dashboard dash = new Dashboard();

// 2. Make the Dashboard visible
dash.setVisible(true);

// 3. Close the current LecturerForm
this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LecturerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtLecturerEmail;
    private javax.swing.JTextField txtLecturerID;
    private javax.swing.JTextField txtLecturerName;
    // End of variables declaration//GEN-END:variables
}
